import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://waldematica.com.br/",
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: "https://waldematica.com.br/extensivo/",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: "https://waldematica.com.br/curso-semiextensivo/",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: "https://waldematica.com.br/curso-profmat/",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: "https://waldematica.com.br/revisao-1a-fase/",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://waldematica.com.br/revisao-2a-fase/",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://waldematica.com.br/padawan/",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://waldematica.com.br/cursos-gratis/",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: "https://waldematica.com.br/blog/",
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://waldematica.com.br/pa-e-pg-no-enem/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/vestibular-unicamp-2027/",
      lastModified: new Date("2026-08-09T01:03:04+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/constante-de-kaprekar/",
      lastModified: new Date("2026-08-08T20:11:31+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/comprimento-da-circunferencia/",
      lastModified: new Date("2026-08-08T19:20:25+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/crescimento-populacional-em-pg/",
      lastModified: new Date("2026-08-08T19:20:10+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/vertice-da-parabola-no-enem/",
      lastModified: new Date("2026-08-08T18:36:12+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/juros-simples-e-juros-compostos/",
      lastModified: new Date("2026-08-08T15:03:22+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/estatistica-no-enem/",
      lastModified: new Date("2026-08-08T13:37:25+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/razao-e-proporcao-no-enem/",
      lastModified: new Date("2026-08-08T12:46:59+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/relacoes-metricas-no-triangulo-retangulo/",
      lastModified: new Date("2026-08-08T12:46:58+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/areas-de-figuras-planas-resumo-enem/",
      lastModified: new Date("2026-08-08T12:46:57+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/equacao-da-reta/",
      lastModified: new Date("2026-08-08T12:46:56+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/funcao-do-2-grau/",
      lastModified: new Date("2026-08-08T12:46:55+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/exercicios-de-probabilidade-lista/",
      lastModified: new Date("2026-08-08T12:46:55+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/formulas-de-area-de-triangulo/",
      lastModified: new Date("2026-08-08T12:46:54+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/escalas-enem/",
      lastModified: new Date("2026-08-08T12:46:53+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/funcao-do-1-grau/",
      lastModified: new Date("2026-08-08T12:46:52+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/10-erros-comuns-no-enem/",
      lastModified: new Date("2026-08-08T12:46:52+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/volume-dos-solidos/",
      lastModified: new Date("2026-08-08T12:46:51+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/o-que-e-logaritmo/",
      lastModified: new Date("2026-08-08T12:46:50+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/estudo-dos-triangulos-enem/",
      lastModified: new Date("2026-08-08T12:46:49+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/produtos-notaveis-fatoracao-vestibular/",
      lastModified: new Date("2026-08-08T12:46:48+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/prova-da-fuvest-imersao/",
      lastModified: new Date("2026-08-08T12:46:47+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/razoes-trigonometricas-triangulo-retangulo/",
      lastModified: new Date("2026-08-08T12:46:47+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/porcentagem-aumento-e-desconto-fuvest/",
      lastModified: new Date("2026-08-08T12:46:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/10-assuntos-que-mais-caem-matematica-enem/",
      lastModified: new Date("2026-08-08T12:46:45+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/como-passar-de-800-pontos-matematica-enem/",
      lastModified: new Date("2026-08-08T12:46:44+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/como-interpretar-problemas-de-matematica/",
      lastModified: new Date("2026-08-08T12:46:43+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/resolver-questoes-discursivas-matematica/",
      lastModified: new Date("2026-08-08T12:46:43+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/como-calcular-mmc-e-mdc-enem/",
      lastModified: new Date("2026-08-08T12:46:42+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/regra-de-tres/",
      lastModified: new Date("2026-08-08T12:46:41+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/analise-combinatoria/",
      lastModified: new Date("2026-08-08T12:46:40+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/provas-do-profmat-resolucoes-comentadas/",
      lastModified: new Date("2026-08-08T12:46:39+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/ganhar-tempo-na-prova-de-matematica/",
      lastModified: new Date("2026-08-08T12:46:38+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/assuntos-de-matematica-que-mais-caem-no-enem/",
      lastModified: new Date("2026-08-08T12:46:38+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/como-estudar-matematica-do-zero/",
      lastModified: new Date("2026-08-08T12:46:37+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/quanto-tempo-estudar-matematica-por-dia/",
      lastModified: new Date("2026-08-08T12:46:36+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/curso-para-o-profmat/",
      lastModified: new Date("2026-08-08T12:46:35+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/tipos-de-angulos/",
      lastModified: new Date("2026-08-08T12:46:35+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/matematica-enem/",
      lastModified: new Date("2026-08-08T12:46:34+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/ciclo-trigonometrico-seno-cosseno/",
      lastModified: new Date("2026-08-08T12:46:33+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/resumo-de-geometria-analitica/",
      lastModified: new Date("2026-08-08T12:46:33+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/o-que-mais-cai-em-matematica-no-enem/",
      lastModified: new Date("2026-08-08T12:46:32+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/como-aprender-matematica/",
      lastModified: new Date("2026-08-08T12:46:30+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/ia-para-estudar-enem/",
      lastModified: new Date("2026-08-08T12:46:29+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/melhor-ia-para-estudar/",
      lastModified: new Date("2026-08-08T12:46:29+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/futuro-da-educacao-com-ia/",
      lastModified: new Date("2026-08-08T12:46:28+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/o-que-sao-quadrilateros/",
      lastModified: new Date("2026-08-08T12:46:27+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/analise-combinatoria-no-enem/",
      lastModified: new Date("2026-08-08T12:46:26+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/circunferencia-na-geometria-analitica/",
      lastModified: new Date("2026-08-08T12:46:25+00:00"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://waldematica.com.br/category/dicas-de-matematica/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/funcoes-matematicas/",
      lastModified: new Date("2026-08-08T18:36:12+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/razao-e-proporcao/",
      lastModified: new Date("2026-08-08T15:03:22+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/geometria-espacial/",
      lastModified: new Date("2026-08-08T12:46:51+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/algebra-para-vestibular/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/matematica-para-o-enem/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/geometria-plana/",
      lastModified: new Date("2026-08-08T19:20:25+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/trigonometria/",
      lastModified: new Date("2026-08-08T12:46:58+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/fuvest/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/unicamp/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/profmat/",
      lastModified: new Date("2026-08-15T19:42:46+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/geometria-analitica/",
      lastModified: new Date("2026-08-08T12:46:56+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/inteligencia-artificial-na-educacao/",
      lastModified: new Date("2026-08-08T12:46:29+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
    {
      url: "https://waldematica.com.br/category/curiosidades-da-matematica/",
      lastModified: new Date("2026-08-08T20:11:31+00:00"),
      changeFrequency: "monthly",
      priority: 0.5,
    },
  ];
}
